---
title: "Download Copernicus CDS data"
output:
  html_document:
    df_print: paged
---
```{r setup}
library(raster)
# library(sf)
# library(tidyverse)
```

# Download the data through a `{Python}` routine

* Copy and paste the request for API from the Copernicus website

```{python download_sst1}
import cdsapi

c = cdsapi.Client()

c.retrieve(
    'reanalysis-era5-single-levels',
    {
        'product_type': 'reanalysis',
        'format': 'netcdf',
        'variable': 'sea_surface_temperature',
        'year': '2019',
        'month': '11',
        'day': [
            '28', '29', '30',
        ],
        'time': [
            '00:00', '06:00', '12:00',
            '18:00',
        ],
        'area': [
            -22, 148, -45,
            157,
        ],
    },
    'download.nc')
```

```{python download_chl}
import cdsapi

c = cdsapi.Client()

c.retrieve(
    'satellite-ocean-colour',
    {
        'format': 'tgz',
        'variable': 'mass_concentration_of_chlorophyll_a',
        'projection': 'regular_latitude_longitude_grid',
        'year': '2019',
        'month': '11',
        'day': [
            '28', '29', '30',
        ],
        'version': '5.0',
    },
    'downloadchl.tar.gz')
```

```{r Copernicus_R_not_used}
################################ Copernicus data *******************************

# Set a key to the keychain 
ecmwfr::wf_set_key(user = "92841",
                   key = "2afb8701-6d08-454e-994b-86198b574eff", 
                   service = "cds")

ecmwfr::wf_get_key(user = "92841")

ecmwfr::wf_datasets(user = "92841", 
                    service = "cds")
## CHL
# 128 satellite-ocean-colour / https://api.ecmwf.int/v1/resources/satellite-ocean-colour
## SSHA
# 137 satellite-sea-level-global / https://api.ecmwf.int/v1/resources/satellite-sea-level-global
## SST
# 139 satellite-sea-surface-temperature / https://api.ecmwf.int/v1/resources/satellite-sea-surface-temperature
# 140 satellite-sea-surface-temperature-complete / https://api.ecmwf.int/v1/resources/satellite-sea-surface-temperature-complete
# 141 satellite-sea-surface-temperature-ensemble-product / https://api.ecmwf.int/v1/resources/satellite-sea-surface-temperature-ensemble-product
# 143 satellite-sst-esa-cci / https://api.ecmwf.int/v1/resources/satellite-sst-esa-cci
## "Fisheries"
# 158 sis-fisheries-abundance / https://api.ecmwf.int/v1/resources/sis-fisheries-abundance
# 159 sis-fisheries-eutrophication / https://api.ecmwf.int/v1/resources/sis-fisheries-eutrophication
# 160 sis-fisheries-ocean-fronts / https://api.ecmwf.int/v1/resources/sis-fisheries-ocean-fronts
# 183 viewer-sis-fisheries-abundance / https://api.ecmwf.int/v1/resources/viewer-sis-fisheries-abundance
# 184 viewer-sis-fisheries-ocean-fronts / https://api.ecmwf.int/v1/resources/viewer-sis-fisheries-ocean-fronts
## "Marine properties"
# 185 viewer-sis-marine-properties / https://api.ecmwf.int/v1/resources/viewer-sis-marine-properties

```

# `{raster}` to wrangle

```{r raster_sst, echo=FALSE}
sst_stack <- raster::stack("./download.nc")
# raster::plot(sst_stack) # Give it a check

sst_raster_mean <- mean(sst_stack)
# raster::plot(sst_raster_mean) # Give it a check

# Export it 
raster::writeRaster(sst_raster_mean,
                    filename = "./data/ms1_australia_RCPs/raster_sst_mean.gpkg",
                    format = "GPKG") 
                    # overwrite = TRUE)
```

```{r daily_means_sst, echo=FALSE}

## Yeah, nah...
sst_stars <- stars::read_stars("./download.nc")
stars::st_dimensions(sst_stars)

sst_mean <- 
  stars::st_apply(sst_stars, MARGIN = 1:2, 
                  FUN = function(x) sum(x, na.rm = TRUE))
plot(sst_mean)

# *************************************


```

```{r raster_chl, echo=FALSE}
## Create an 'Extent' object on which to crop original .nc files
# (xmin, xmax, ymin, ymax) = (long_min, long_max, lat_min, lat_max)
ext_crop <- as(raster::extent(148, 158, -45, -22), 'SpatialPolygons')
# Assign 'crs'
crs(ext_crop) <- "+proj=longlat +datum=WGS84 +no_defs"

# ***************** Open and crop each file ************************************
## Filenames
filenames <- as.list(list.files(path = "./downloadchl",
                               pattern = ".nc$",
                               full.names = TRUE))

## Open each file listed on 'filenames'
chl_stack <- purrr::map(filenames, raster::stack, varname = "chlor_a")
# raster::plot(chl_stack[[3]]) # Give it a check

## Crop each element in the list with the desired extent
chl_stack <- purrr::map(chl_stack, raster::crop, ext_crop)
# raster::plot(chl_stack[[3]]) # Give it a check

chl_stack <- raster::stack(chl_stack)

chl_raster_mean <- mean(chl_stack)
# raster::plot(chl_raster_mean) # Give it a check

# Export it 
raster::writeRaster(chl_raster_mean,
                    filename = "./data/ms1_australia_RCPs/raster_chl_mean.gpkg",
                    format = "GPKG")
```


